POST http://127.0.0.1:8081/api/v1/events
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhhdXNjaGlsZC10aW1AdC1vbmxpbmUuZGUiLCJleHAiOjE3NjIxOTY1NzcsInVzZXJJZCI6MX0.08kjBRc3rzuCuVA50FHAJJ8sD-jNVhrgK-fj2KV5YwM

{
  "name": "New Event",
  "description": "This is a new event created for testing.",
  "dateTime": "2024-07-01T10:00:00Z",
  "location": "123 Test St, Test City"
}